name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      database:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 5
        env:
          MYSQL_DATABASE: "db_java_spring_boot_ecommerce_bd02"
          MYSQL_PASSWORD: "33063306"
          MYSQL_ROOT_PASSWORD: "33063306"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test